'use client';

import Link from 'next/link';
import { Shield } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 bg-white/95 backdrop-blur-sm border-b border-gray-100 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="flex items-center gap-2">
              <div className="bg-blue-600 rounded-xl p-2">
                <Shield className="w-6 h-6 text-white" />
              </div>
              <span className="text-xl font-bold text-gray-900">SubShield</span>
            </Link>
            <Link
              href="/analyze"
              className="bg-blue-600 text-white px-5 py-2.5 rounded-lg font-medium hover:bg-blue-700 transition-all"
            >
              Analyze Contract
            </Link>
          </div>
        </div>
      </nav>

      <main className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
          <p className="text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

          <div className="prose prose-gray max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-600 mb-4">
                By accessing or using SubShield (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Description of Service</h2>
              <p className="text-gray-600 mb-4">
                SubShield provides AI-powered analysis of construction subcontracts to help identify potentially risky clauses and suggest negotiation language. The Service includes:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Contract document upload and parsing</li>
                <li>AI-powered risk analysis</li>
                <li>Risk scoring and recommendations</li>
                <li>Suggested negotiation scripts</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Important Disclaimer - Not Legal Advice</h2>
              <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4">
                <p className="text-amber-800 font-semibold mb-2">PLEASE READ THIS SECTION CAREFULLY</p>
                <p className="text-amber-700">
                  SubShield is NOT a law firm and does NOT provide legal advice. The analysis, recommendations, and negotiation scripts provided by SubShield are for informational purposes only and should not be construed as legal advice.
                </p>
              </div>
              <p className="text-gray-600 mb-4">
                You acknowledge and agree that:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>SubShield&apos;s analysis is generated by artificial intelligence and may not identify all risks in your contract</li>
                <li>The Service is not a substitute for review by a licensed construction attorney</li>
                <li>You should consult with a qualified attorney before signing any contract</li>
                <li>SubShield is not responsible for any decisions made based on the analysis provided</li>
                <li>Laws vary by jurisdiction, and the Service may not account for state-specific regulations</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">4. User Responsibilities</h2>
              <p className="text-gray-600 mb-4">When using SubShield, you agree to:</p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Provide accurate information</li>
                <li>Only upload contracts you have the right to analyze</li>
                <li>Not use the Service for any unlawful purpose</li>
                <li>Not attempt to reverse engineer, hack, or disrupt the Service</li>
                <li>Not use automated systems to access the Service beyond normal use</li>
                <li>Comply with all applicable laws and regulations</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Payment Terms</h2>
              <p className="text-gray-600 mb-4">
                <strong>Pricing:</strong> Full contract analysis is available for a one-time fee of $147 per contract. A free preview is provided before purchase.
              </p>
              <p className="text-gray-600 mb-4">
                <strong>Refund Policy:</strong> We offer a 30-day money-back guarantee. If you are not satisfied with your analysis, contact us at support@trysubshield.com within 30 days of purchase for a full refund.
              </p>
              <p className="text-gray-600 mb-4">
                <strong>Payment Processing:</strong> Payments are processed securely through Stripe. By making a purchase, you also agree to Stripe&apos;s terms of service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Intellectual Property</h2>
              <p className="text-gray-600 mb-4">
                <strong>Your Content:</strong> You retain all rights to the contracts and documents you upload. We claim no ownership over your content.
              </p>
              <p className="text-gray-600 mb-4">
                <strong>Our Content:</strong> The SubShield service, including its design, features, analysis methodologies, and negotiation templates, is owned by SubShield and protected by intellectual property laws.
              </p>
              <p className="text-gray-600 mb-4">
                <strong>Analysis Output:</strong> You are granted a license to use the analysis and negotiation scripts generated for your contracts for your personal or business use.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Privacy and Data Handling</h2>
              <p className="text-gray-600 mb-4">
                Your use of the Service is also governed by our <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>. Key points:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Contract documents are deleted after analysis is complete</li>
                <li>We do not share your contract content with third parties (except for AI processing)</li>
                <li>Payment information is handled securely by Stripe</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Limitation of Liability</h2>
              <p className="text-gray-600 mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, SUBSHIELD SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Loss of profits or business opportunities</li>
                <li>Damages arising from contract disputes</li>
                <li>Losses related to decisions made based on our analysis</li>
                <li>Any damages resulting from unidentified contract risks</li>
              </ul>
              <p className="text-gray-600 mt-4">
                Our total liability for any claims arising from use of the Service shall not exceed the amount you paid for the Service in the 12 months prior to the claim.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Disclaimer of Warranties</h2>
              <p className="text-gray-600 mb-4">
                THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Warranties of merchantability or fitness for a particular purpose</li>
                <li>Warranties that the analysis will identify all contract risks</li>
                <li>Warranties that the Service will be uninterrupted or error-free</li>
                <li>Warranties regarding the accuracy of AI-generated content</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Indemnification</h2>
              <p className="text-gray-600 mb-4">
                You agree to indemnify and hold harmless SubShield, its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable attorney fees) arising from:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any third-party rights</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Modifications to Service and Terms</h2>
              <p className="text-gray-600 mb-4">
                We reserve the right to modify or discontinue the Service at any time without notice. We may also update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Governing Law</h2>
              <p className="text-gray-600 mb-4">
                These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law provisions.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">13. Dispute Resolution</h2>
              <p className="text-gray-600 mb-4">
                Any disputes arising from these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">14. Severability</h2>
              <p className="text-gray-600 mb-4">
                If any provision of these Terms is found to be unenforceable, the remaining provisions shall remain in full force and effect.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">15. Contact Information</h2>
              <p className="text-gray-600 mb-4">
                For questions about these Terms, please contact us at:
              </p>
              <p className="text-gray-600">
                <strong>Email:</strong> <a href="mailto:support@trysubshield.com" className="text-blue-600 hover:underline">support@trysubshield.com</a>
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-50 border-t border-gray-200 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-gray-500 text-sm">
          <p>© {new Date().getFullYear()} SubShield. All rights reserved.</p>
          <div className="flex justify-center gap-6 mt-4">
            <Link href="/privacy" className="hover:text-gray-900">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-gray-900">Terms of Service</Link>
            <a href="mailto:support@trysubshield.com" className="hover:text-gray-900">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
